name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to registry
      uses: azure/docker-login@v1
      with:
        login-server: 'registry.cloud.actigraph.com'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image for uptime-api
      run: cd uptime-api && docker build . --file Dockerfile --tag registry.cloud.actigraph.com/uptime-api:latest 
    - name: Publish to Registry uptime-api
      run: docker push registry.cloud.actigraph.com/uptime-api:latest 

